import React, { useState } from 'react';
import {
  Building2, Plus, Edit2, Trash2, CheckCircle2, Check, Building, Phone, Mail, MapPin, Landmark, ShieldCheck, Sparkles, ArrowRight, Download, Upload, FileCode2, RefreshCw, Calendar, Globe, Coins, FileText, AlertCircle, HelpCircle, QrCode, Copy,
} from 'lucide-react';
import { SellerInfo, TallyConfig } from '../types';
import { INDIAN_STATES, getStateCodeByName, extractStateCodeFromGstin, extractPanFromGstin } from '../utils/gstUtils';
import { fetchCompaniesFromTally, parseCompaniesXML, DEFAULT_TALLY_CONFIG } from '../services/tallyCompanyImportService';

interface CompanyProfileViewProps {
  companies: SellerInfo[];
  currentCompany: SellerInfo;
  onSelectCompany: (company: SellerInfo) => void;
  onAddCompany: (company: SellerInfo) => void;
  onUpdateCompany: (company: SellerInfo) => void;
  onDeleteCompany: (id: string) => void;
  tallyConfig?: TallyConfig;
}

export const CompanyProfileView: React.FC<CompanyProfileViewProps> = ({
  companies, currentCompany, onSelectCompany, onAddCompany, onUpdateCompany, onDeleteCompany, tallyConfig = DEFAULT_TALLY_CONFIG,
}) => {
  const [isEditing, setIsEditing] = useState<boolean>(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [isImportingFromTally, setIsImportingFromTally] = useState<boolean>(false);
  const [isXmlPasteOpen, setIsXmlPasteOpen] = useState<boolean>(false);
  const [pastedXml, setPastedXml] = useState<string>('');
  const [name, setName] = useState(''); const [mailingName, setMailingName] = useState(''); const [address, setAddress] = useState(''); const [state, setState] = useState('Delhi'); const [stateCode, setStateCode] = useState('07'); const [country, setCountry] = useState('India'); const [pincode, setPincode] = useState(''); const [phone, setPhone] = useState(''); const [mobile, setMobile] = useState(''); const [email, setEmail] = useState(''); const [website, setWebsite] = useState(''); const [gstin, setGstin] = useState(''); const [pan, setPan] = useState(''); const [financialYearFrom, setFinancialYearFrom] = useState('2025-04-01'); const [booksBeginningFrom, setBooksBeginningFrom] = useState('2025-04-01'); const [currencySymbol, setCurrencySymbol] = useState('₹'); const [currencyFormalName, setCurrencyFormalName] = useState('INR'); const [bankName, setBankName] = useState(''); const [bankAccountNo, setBankAccountNo] = useState(''); const [bankIfsc, setBankIfsc] = useState(''); const [bankBranch, setBankBranch] = useState(''); const [upiId, setUpiId] = useState('');
  const [notification, setNotification] = useState<{text:string;type:'success'|'error'|'info'}|null>(null);

  const resetForm=()=>{setName('');setMailingName('');setAddress('');setState('Delhi');setStateCode('07');setCountry('India');setPincode('');setPhone('');setMobile('');setEmail('');setWebsite('');setGstin('');setPan('');setFinancialYearFrom('2025-04-01');setBooksBeginningFrom('2025-04-01');setCurrencySymbol('₹');setCurrencyFormalName('INR');setBankName('');setBankAccountNo('');setBankIfsc('');setBankBranch('');setUpiId('');setEditingId(null);setIsEditing(false);};
  const handleOpenAdd=()=>{resetForm();setIsEditing(true);};
  const handleOpenEdit=(comp:SellerInfo)=>{setEditingId(comp.id||comp.name);setName(comp.name);setMailingName(comp.mailingName||comp.tradeName||comp.name);setAddress(comp.address||'');setState(comp.state||'Delhi');setStateCode(comp.stateCode||getStateCodeByName(comp.state)||'07');setCountry(comp.country||'India');setPincode(comp.pincode||'');setPhone(comp.phone||'');setMobile(comp.mobile||'');setEmail(comp.email||'');setWebsite(comp.website||'');setGstin(comp.gstin||'');setPan(comp.pan||(comp.gstin?extractPanFromGstin(comp.gstin):''));setFinancialYearFrom(comp.financialYearFrom||'2025-04-01');setBooksBeginningFrom(comp.booksBeginningFrom||'2025-04-01');setCurrencySymbol(comp.currencySymbol||'₹');setCurrencyFormalName(comp.currencyFormalName||'INR');setBankName(comp.bankName||'');setBankAccountNo(comp.bankAccountNo||'');setBankIfsc(comp.bankIfsc||'');setBankBranch(comp.bankBranch||'');setUpiId(comp.upiId||'');setIsEditing(true);};
  const handleGstinChange=(val:string)=>{const upper=val.toUpperCase().trim();setGstin(upper);if(upper.length>=2){const code=extractStateCodeFromGstin(upper);if(code){setStateCode(code);const matchState=INDIAN_STATES.find(s=>s.code===code);if(matchState)setState(matchState.name);}}if(upper.length>=10){const extractedPan=extractPanFromGstin(upper);if(extractedPan)setPan(extractedPan);}};
  const handleStateChange=(selected:string)=>{setState(selected);const code=getStateCodeByName(selected);if(code)setStateCode(code);};
  const handleSaveCompany=(e:React.FormEvent)=>{e.preventDefault();if(!name.trim()){setNotification({text:'Company Name is required.',type:'error'});return;}const companyData:SellerInfo={id:editingId||`comp-${Date.now()}-${name.replace(/[^a-zA-Z0-9]/g,'').toLowerCase()}`,name:name.trim().toUpperCase(),tradeName:mailingName&&mailingName!==name?mailingName.trim():undefined,mailingName:mailingName.trim()||name.trim().toUpperCase(),address:address.trim(),state:state.trim(),stateCode:stateCode.trim()||'07',country:country.trim()||'India',pincode:pincode.trim(),phone:phone.trim()||mobile.trim(),mobile:mobile.trim(),email:email.trim(),website:website.trim(),gstin:gstin.trim().toUpperCase(),pan:pan.trim().toUpperCase()||(gstin?extractPanFromGstin(gstin):''),financialYearFrom,booksBeginningFrom,currencySymbol:currencySymbol||'₹',currencyFormalName:currencyFormalName||'INR',bankName:bankName.trim(),bankAccountNo:bankAccountNo.trim(),bankIfsc:bankIfsc.trim().toUpperCase(),bankBranch:bankBranch.trim(),upiId:upiId.trim(),isDefault:currentCompany.id===editingId||companies.length===0};if(editingId)onUpdateCompany(companyData);else onAddCompany(companyData);setNotification({text:`✅ Company "${companyData.name}" saved successfully!`,type:'success'});resetForm();setTimeout(()=>setNotification(null),4000);};

  const handleImportFromTallyPrime=async()=>{setIsImportingFromTally(true);setNotification({text:'Tally Prime se current Company Master read ho raha hai...',type:'info'});try{const importedCompanies=await fetchCompaniesFromTally(tallyConfig);importedCompanies.forEach(comp=>{const exists=companies.find(c=>c.name.toLowerCase()===comp.name.toLowerCase()||(comp.gstin&&c.gstin===comp.gstin));if(exists)onUpdateCompany({...comp,id:exists.id});else onAddCompany(comp);});onSelectCompany(importedCompanies[0]);setNotification({text:`🎉 Tally se ${importedCompanies.length} Company profile import hui. Active: "${importedCompanies[0].name}"`,type:'success'});}catch(err:any){console.error(err);setNotification({text:`❌ Tally Company Import failed: ${err.message||'Unknown error'}`,type:'error'});}finally{setIsImportingFromTally(false);setTimeout(()=>setNotification(null),6000);}};
  const handleProcessPastedXml=()=>{if(!pastedXml.trim()){setNotification({text:'Please paste Tally XML content first.',type:'error'});return;}try{const parsedCompanies=parseCompaniesXML(pastedXml);if(parsedCompanies.length){parsedCompanies.forEach(comp=>{const exists=companies.find(c=>c.name.toLowerCase()===comp.name.toLowerCase()||(comp.gstin&&c.gstin===comp.gstin));if(exists)onUpdateCompany({...comp,id:exists.id});else onAddCompany(comp);});onSelectCompany(parsedCompanies[0]);setIsXmlPasteOpen(false);setPastedXml('');setNotification({text:`🎉 XML se ${parsedCompanies.length} Company profile import hui.`,type:'success'});}else setNotification({text:'❌ Company master nahi mila.',type:'error'});}catch(e:any){setNotification({text:`❌ XML parse failed: ${e.message||e}`,type:'error'});}};

  return <div className="flex-1 bg-slate-50 min-h-screen p-5 md:p-8">
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div><div className="flex items-center gap-2 text-blue-600 text-sm font-semibold"><Building2 className="w-5 h-5"/>Company Master</div><h1 className="text-2xl font-bold text-slate-900 mt-1">Company Profile</h1><p className="text-sm text-slate-500 mt-1">Tally se current company ki complete profile import karein.</p></div>
        <div className="flex gap-2"><button onClick={handleImportFromTallyPrime} disabled={isImportingFromTally} className="px-4 py-2.5 rounded-lg bg-blue-600 text-white font-semibold flex items-center gap-2 disabled:opacity-60">{isImportingFromTally?<RefreshCw className="w-4 h-4 animate-spin"/>:<Download className="w-4 h-4"/>}{isImportingFromTally?'Importing...':'Import Current Tally Company'}</button><button onClick={handleOpenAdd} className="px-4 py-2.5 rounded-lg bg-slate-900 text-white font-semibold flex items-center gap-2"><Plus className="w-4 h-4"/>Add Company</button></div>
      </div>
      {notification&&<div className={`rounded-xl p-3 border ${notification.type==='error'?'border-rose-300 bg-rose-50 text-rose-700':notification.type==='success'?'border-emerald-300 bg-emerald-50 text-emerald-700':'border-blue-300 bg-blue-50 text-blue-700'}`}>{notification.text}</div>}
      <div className="grid md:grid-cols-2 gap-4">{companies.map(comp=><div key={comp.id||comp.name} className={`bg-white border rounded-2xl p-5 ${currentCompany.id===comp.id?'border-blue-500 ring-2 ring-blue-100':'border-slate-200'}`}><div className="flex items-start justify-between gap-3"><div><div className="font-bold text-slate-900">{comp.name}</div><div className="text-xs font-mono text-blue-600 mt-1">{comp.gstin||'GSTIN not set'}</div></div><button onClick={()=>onSelectCompany(comp)} className="text-xs px-3 py-1.5 rounded-lg bg-slate-100">{currentCompany.id===comp.id?'Active':'Select'}</button></div><div className="text-sm text-slate-600 mt-3 space-y-1"><div><MapPin className="inline w-4 h-4 mr-1"/>{comp.address||'Address not set'}</div><div><Phone className="inline w-4 h-4 mr-1"/>{comp.mobile||comp.phone||'Mobile not set'}</div><div><Mail className="inline w-4 h-4 mr-1"/>{comp.email||'Email not set'}</div><div>State: {comp.state||'-'} ({comp.stateCode||'-'})</div></div><div className="flex gap-2 mt-4"><button onClick={()=>handleOpenEdit(comp)} className="text-xs px-3 py-1.5 rounded-lg bg-slate-100"><Edit2 className="inline w-3.5 h-3.5 mr-1"/>Edit</button><button onClick={()=>onDeleteCompany(comp.id||comp.name)} className="text-xs px-3 py-1.5 rounded-lg bg-rose-50 text-rose-700"><Trash2 className="inline w-3.5 h-3.5 mr-1"/>Delete</button></div></div>)}</div>
      {isEditing&&<div className="bg-white rounded-2xl border border-slate-200 p-6"><h2 className="text-lg font-bold mb-4">{editingId?'Edit':'Add'} Company</h2><form onSubmit={handleSaveCompany} className="grid md:grid-cols-2 gap-4"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Company name" className="border rounded-lg px-3 py-2" required/><input value={mailingName} onChange={e=>setMailingName(e.target.value)} placeholder="Mailing / trade name" className="border rounded-lg px-3 py-2"/><textarea value={address} onChange={e=>setAddress(e.target.value)} placeholder="Address" className="border rounded-lg px-3 py-2 md:col-span-2"/><select value={state} onChange={e=>handleStateChange(e.target.value)} className="border rounded-lg px-3 py-2">{INDIAN_STATES.map(s=><option key={s.code} value={s.name}>{s.name}</option>)}</select><input value={pincode} onChange={e=>setPincode(e.target.value)} placeholder="Pincode" className="border rounded-lg px-3 py-2"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone" className="border rounded-lg px-3 py-2"/><input value={mobile} onChange={e=>setMobile(e.target.value)} placeholder="Mobile" className="border rounded-lg px-3 py-2"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="border rounded-lg px-3 py-2"/><input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="Website" className="border rounded-lg px-3 py-2"/><input value={gstin} onChange={e=>handleGstinChange(e.target.value)} placeholder="GSTIN" className="border rounded-lg px-3 py-2"/><input value={pan} onChange={e=>setPan(e.target.value)} placeholder="PAN" className="border rounded-lg px-3 py-2"/><input value={bankName} onChange={e=>setBankName(e.target.value)} placeholder="Bank name" className="border rounded-lg px-3 py-2"/><input value={bankAccountNo} onChange={e=>setBankAccountNo(e.target.value)} placeholder="Bank account" className="border rounded-lg px-3 py-2"/><input value={bankIfsc} onChange={e=>setBankIfsc(e.target.value)} placeholder="IFSC" className="border rounded-lg px-3 py-2"/><div className="md:col-span-2 flex gap-2"><button type="submit" className="px-4 py-2 rounded-lg bg-blue-600 text-white">Save Company</button><button type="button" onClick={resetForm} className="px-4 py-2 rounded-lg bg-slate-100">Cancel</button></div></form></div>}
    </div>
  </div>;
};
