import React, { useEffect, useMemo, useState } from 'react';
import { Download, Plus, Trash2, Save, FileText, ShieldCheck } from 'lucide-react';
import { Invoice, SellerInfo } from '../types';
import { buildGstr1JsonPayload } from '../services/gstr1Service';
import { buildFullGstr1Json, downloadFullGstr1Json, emptyGstr1ExtendedData, Gstr1ExtendedData, Gstr1NoteRow, Gstr1ExportRow, Gstr1AdvanceRow, Gstr1NilRow, Gstr1AmendmentRow, Gstr1EcomRow, loadGstr1ExtendedData, saveGstr1ExtendedData } from '../services/gstr1AdvancedService';

interface Props { invoices: Invoice[]; sellerInfo: SellerInfo; period: string; }
const uid = () => `${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const input = 'w-full bg-slate-950 border border-slate-700 rounded-lg px-2.5 py-2 text-xs text-white outline-none focus:border-emerald-500';
const num = (v: string) => Number(v) || 0;

export const Gstr1AdvancedView: React.FC<Props> = ({ invoices, sellerInfo, period }) => {
  const [data, setData] = useState<Gstr1ExtendedData>(() => loadGstr1ExtendedData(sellerInfo, period));
  const [section, setSection] = useState<'notes'|'exports'|'advances'|'nil'|'amendments'|'ecom'>('notes');
  const [saved, setSaved] = useState(false);
  useEffect(() => setData(loadGstr1ExtendedData(sellerInfo, period)), [sellerInfo.gstin, sellerInfo.name, period]);
  const base = useMemo(() => buildGstr1JsonPayload({} as any), []);
  // The real base payload is reconstructed below from the invoice set so this panel is standalone.
  const makeBase = () => {
    const grouped: Record<string, any[]> = {};
    invoices.forEach(i => {
      if (!i.gstin) return;
      const pos = i.stateCode || sellerInfo.stateCode || '07';
      const row = { inum:i.invoiceNo, idt:i.invoiceDate, val:i.grandTotal, pos, rchrg:'N', inv_typ:'R', itms:(i.items||[]).map((x,n)=>({num:n+1,itm_det:{rt:x.gstRate,txval:x.taxableAmount,iamt:x.igstAmount,camt:x.cgstAmount,samt:x.sgstAmount,csamt:0}})) };
      (grouped[i.gstin.toUpperCase()] ||= []).push(row);
    });
    return { gstin:(sellerInfo.gstin||'').toUpperCase(), fp:period, gt:invoices.reduce((a,i)=>a+i.grandTotal,0), cur_gt:invoices.reduce((a,i)=>a+i.grandTotal,0), version:'GST3.1.4', hash:'hash', ...(Object.keys(grouped).length?{b2b:Object.entries(grouped).map(([ctin,inv])=>({ctin,inv}))}:{}), doc_issue:{doc_det:[]} };
  };
  const fullJson = useMemo(() => buildFullGstr1Json(makeBase(), data), [invoices, sellerInfo, data, period]);
  const update = (next: Gstr1ExtendedData) => { setData(next); saveGstr1ExtendedData(sellerInfo, period, next); setSaved(true); setTimeout(()=>setSaved(false),1500); };
  const add = <T,>(name: keyof Gstr1ExtendedData, row: T) => update({ ...data, [name]: [...(data[name] as T[]), row] } as Gstr1ExtendedData);
  const remove = (name: keyof Gstr1ExtendedData, id: string) => update({ ...data, [name]: (data[name] as any[]).filter(x=>x.id!==id) } as Gstr1ExtendedData);

  const addNote = (category: 'registered'|'unregistered') => {
    const row: Gstr1NoteRow = { id:uid(), typ:'C', ntty:'C', nt_num:'CN-001', nt_dt:new Date().toISOString().slice(0,10), p_gst:category==='registered'?'':'', val:0, pos:sellerInfo.stateCode||'07', sply_ty:'INTRA', itms:[{num:1,itm_det:{rt:18,txval:0,iamt:0,camt:0,samt:0,csamt:0}}] };
    add(category==='registered'?'notesRegistered':'notesUnregistered', row);
  };
  const addExport = () => add('exports', {id:uid(),typ:'WOPAY',exp_typ:'WOPAY',inum:'EXP-001',idt:new Date().toISOString().slice(0,10),val:0,txval:0,rt:0,iamt:0,csamt:0} as Gstr1ExportRow);
  const addAdvance = (adjust=false) => add(adjust?'advanceAdjustments':'advances', {id:uid(),typ:adjust?'TXPD':'AT',pos:sellerInfo.stateCode||'07',sply_ty:'INTRA',rt:18,ad_amt:0,iamt:0,camt:0,samt:0,csamt:0} as Gstr1AdvanceRow);
  const addNil = () => add('nilExempt',{id:uid(),sply_typ:'NIL',nil_amt:0,ex_amt:0,ngsup_amt:0} as Gstr1NilRow);
  const addAmend = () => add('amendments',{id:uid(),table:'B2B',originalNo:'',originalDate:'',originalPeriod:'',value:0,taxable:0,rate:18,igst:0,cgst:0,sgst:0} as Gstr1AmendmentRow);
  const addEcom = (amend=false) => add(amend?'ecomAmendments':'ecom',{id:uid(),etin:'',typ:'E',pos:sellerInfo.stateCode||'07',txval:0,rt:18,iamt:0,camt:0,samt:0,csamt:0} as Gstr1EcomRow);

  const field = (label:string, value:any, onChange:(v:string)=>void, type='text') => <label className="block"><span className="block text-[10px] uppercase text-slate-400 mb-1">{label}</span><input className={input} type={type} value={value ?? ''} onChange={e=>onChange(e.target.value)} /></label>;
  const tabs = [['notes','Credit / Debit Notes'],['exports','Exports / SEZ'],['advances','Advances'],['nil','Nil / Exempt / Non-GST'],['amendments','Amendments'],['ecom','E-Commerce']];

  return <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-5">
    <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-3">
      <div><h2 className="text-lg font-bold text-white flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-emerald-400"/>Full GSTR-1 Data</h2><p className="text-xs text-slate-400 mt-1">Additional GSTR-1 sections that are not represented by normal sales invoices.</p></div>
      <div className="flex gap-2 flex-wrap"><button onClick={()=>update(data)} className="px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-xs text-white flex gap-2 items-center"><Save className="w-3.5 h-3.5"/>Save</button><button onClick={()=>downloadFullGstr1Json(makeBase(),data,sellerInfo,period)} className="px-3 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-xs font-bold text-white flex gap-2 items-center"><Download className="w-3.5 h-3.5"/>Download Full GSTR-1 JSON</button></div>
    </div>
    {saved && <div className="text-xs text-emerald-400">✓ Saved locally for {sellerInfo.gstin} / {period}</div>}
    <div className="flex gap-1 overflow-x-auto border-b border-slate-800 pb-2">{tabs.map(([id,label])=><button key={id} onClick={()=>setSection(id as any)} className={`px-3 py-2 rounded-lg text-xs whitespace-nowrap ${section===id?'bg-emerald-600 text-white':'bg-slate-950 text-slate-400 hover:text-white'}`}>{label}</button>)}</div>

    {section==='notes' && <div className="space-y-4"><div className="flex gap-2"><button onClick={()=>addNote('registered')} className="px-3 py-2 bg-blue-600 rounded-lg text-xs text-white flex gap-1"><Plus className="w-3 h-3"/>Registered Note</button><button onClick={()=>addNote('unregistered')} className="px-3 py-2 bg-indigo-600 rounded-lg text-xs text-white flex gap-1"><Plus className="w-3 h-3"/>Unregistered Note</button></div>{[...data.notesRegistered.map(x=>[x,'notesRegistered'] as const),...data.notesUnregistered.map(x=>[x,'notesUnregistered'] as const)].map(([r,name])=><div key={r.id} className="grid grid-cols-2 md:grid-cols-5 gap-2 p-3 bg-slate-950 rounded-xl border border-slate-800">{field('Type',r.typ,v=>update({...data,[name]:(data[name] as Gstr1NoteRow[]).map(x=>x.id===r.id?{...x,typ:v as any,ntty:v as any}:x)}))}{field('Note No.',r.nt_num,v=>update({...data,[name]:(data[name] as Gstr1NoteRow[]).map(x=>x.id===r.id?{...x,nt_num:v}:x)}))}{field('Date',r.nt_dt,v=>update({...data,[name]:(data[name] as Gstr1NoteRow[]).map(x=>x.id===r.id?{...x,nt_dt:v}:x)}),'date')}{field('Recipient GSTIN',r.p_gst,v=>update({...data,[name]:(data[name] as Gstr1NoteRow[]).map(x=>x.id===r.id?{...x,p_gst:v}:x)}))}{field('Value',r.val,v=>update({...data,[name]:(data[name] as Gstr1NoteRow[]).map(x=>x.id===r.id?{...x,val:num(v)}:x)}),'number')}<button onClick={()=>remove(name,r.id)} className="text-rose-400 text-xs flex items-center gap-1"><Trash2 className="w-3.5 h-3.5"/>Delete</button></div>)}</div>}

    {section==='exports' && <div className="space-y-3"><button onClick={addExport} className="px-3 py-2 bg-emerald-600 rounded-lg text-xs text-white flex gap-1"><Plus className="w-3 h-3"/>Add Export Invoice</button>{data.exports.map(r=><div key={r.id} className="grid grid-cols-2 md:grid-cols-6 gap-2 p-3 bg-slate-950 rounded-xl border border-slate-800">{field('Type',r.typ,v=>update({...data,exports:data.exports.map(x=>x.id===r.id?{...x,typ:v as any,exp_typ:v as any}:x)}))}{field('Invoice No.',r.inum,v=>update({...data,exports:data.exports.map(x=>x.id===r.id?{...x,inum:v}:x)}))}{field('Date',r.idt,v=>update({...data,exports:data.exports.map(x=>x.id===r.id?{...x,idt:v}:x)}),'date')}{field('Invoice Value',r.val,v=>update({...data,exports:data.exports.map(x=>x.id===r.id?{...x,val:num(v)}:x)}),'number')}{field('Taxable',r.txval,v=>update({...data,exports:data.exports.map(x=>x.id===r.id?{...x,txval:num(v)}:x)}),'number')}{field('IGST',r.iamt,v=>update({...data,exports:data.exports.map(x=>x.id===r.id?{...x,iamt:num(v)}:x)}),'number')}<button onClick={()=>remove('exports',r.id)} className="text-rose-400 text-xs"><Trash2 className="w-3.5 h-3.5"/></button></div>)}</div>}

    {section==='advances' && <div className="space-y-3"><div className="flex gap-2"><button onClick={()=>addAdvance(false)} className="px-3 py-2 bg-emerald-600 rounded-lg text-xs text-white"><Plus className="w-3 h-3 inline"/> Advance Received</button><button onClick={()=>addAdvance(true)} className="px-3 py-2 bg-blue-600 rounded-lg text-xs text-white"><Plus className="w-3 h-3 inline"/> Advance Adjusted</button></div>{[...data.advances.map(x=>[x,'advances'] as const),...data.advanceAdjustments.map(x=>[x,'advanceAdjustments'] as const)].map(([r,name])=><div key={r.id} className="grid grid-cols-2 md:grid-cols-6 gap-2 p-3 bg-slate-950 rounded-xl border border-slate-800">{field('POS',r.pos,v=>update({...data,[name]:(data[name] as Gstr1AdvanceRow[]).map(x=>x.id===r.id?{...x,pos:v}:x)}))}{field('Supply',r.sply_ty,v=>update({...data,[name]:(data[name] as Gstr1AdvanceRow[]).map(x=>x.id===r.id?{...x,sply_ty:v as any}:x)}))}{field('Rate',r.rt,v=>update({...data,[name]:(data[name] as Gstr1AdvanceRow[]).map(x=>x.id===r.id?{...x,rt:num(v)}:x)}),'number')}{field('Advance',r.ad_amt,v=>update({...data,[name]:(data[name] as Gstr1AdvanceRow[]).map(x=>x.id===r.id?{...x,ad_amt:num(v)}:x)}),'number')}{field('IGST',r.iamt,v=>update({...data,[name]:(data[name] as Gstr1AdvanceRow[]).map(x=>x.id===r.id?{...x,iamt:num(v)}:x)}),'number')}{field('CGST',r.camt,v=>update({...data,[name]:(data[name] as Gstr1AdvanceRow[]).map(x=>x.id===r.id?{...x,camt:num(v)}:x)}),'number')}<button onClick={()=>remove(name,r.id)} className="text-rose-400"><Trash2 className="w-3.5 h-3.5"/></button></div>)}</div>}

    {section==='nil' && <div className="space-y-3"><button onClick={addNil} className="px-3 py-2 bg-emerald-600 rounded-lg text-xs text-white"><Plus className="w-3 h-3 inline"/> Add Nil / Exempt / Non-GST</button>{data.nilExempt.map(r=><div key={r.id} className="grid grid-cols-2 md:grid-cols-4 gap-2 p-3 bg-slate-950 rounded-xl border border-slate-800">{field('Supply Type',r.sply_typ,v=>update({...data,nilExempt:data.nilExempt.map(x=>x.id===r.id?{...x,sply_typ:v}:x)}))}{field('Nil Rated',r.nil_amt,v=>update({...data,nilExempt:data.nilExempt.map(x=>x.id===r.id?{...x,nil_amt:num(v)}:x)}),'number')}{field('Exempt',r.ex_amt,v=>update({...data,nilExempt:data.nilExempt.map(x=>x.id===r.id?{...x,ex_amt:num(v)}:x)}),'number')}{field('Non-GST',r.ngsup_amt,v=>update({...data,nilExempt:data.nilExempt.map(x=>x.id===r.id?{...x,ngsup_amt:num(v)}:x)}),'number')}<button onClick={()=>remove('nilExempt',r.id)} className="text-rose-400"><Trash2 className="w-3.5 h-3.5"/></button></div>)}</div>}

    {section==='amendments' && <div className="space-y-3"><button onClick={addAmend} className="px-3 py-2 bg-emerald-600 rounded-lg text-xs text-white"><Plus className="w-3 h-3 inline"/> Add Amendment</button>{data.amendments.map(r=><div key={r.id} className="grid grid-cols-2 md:grid-cols-6 gap-2 p-3 bg-slate-950 rounded-xl border border-slate-800">{field('Table',r.table,v=>update({...data,amendments:data.amendments.map(x=>x.id===r.id?{...x,table:v as any}:x)}))}{field('Original No.',r.originalNo,v=>update({...data,amendments:data.amendments.map(x=>x.id===r.id?{...x,originalNo:v}:x)}))}{field('Original Period',r.originalPeriod,v=>update({...data,amendments:data.amendments.map(x=>x.id===r.id?{...x,originalPeriod:v}:x)}))}{field('Value',r.value,v=>update({...data,amendments:data.amendments.map(x=>x.id===r.id?{...x,value:num(v)}:x)}),'number')}{field('Taxable',r.taxable,v=>update({...data,amendments:data.amendments.map(x=>x.id===r.id?{...x,taxable:num(v)}:x)}),'number')}{field('Rate',r.rate,v=>update({...data,amendments:data.amendments.map(x=>x.id===r.id?{...x,rate:num(v)}:x)}),'number')}<button onClick={()=>remove('amendments',r.id)} className="text-rose-400"><Trash2 className="w-3.5 h-3.5"/></button></div>)}</div>}

    {section==='ecom' && <div className="space-y-3"><div className="flex gap-2"><button onClick={()=>addEcom(false)} className="px-3 py-2 bg-emerald-600 rounded-lg text-xs text-white"><Plus className="w-3 h-3 inline"/> Add E-Commerce Supply</button><button onClick={()=>addEcom(true)} className="px-3 py-2 bg-blue-600 rounded-lg text-xs text-white"><Plus className="w-3 h-3 inline"/> Add E-Commerce Amendment</button></div>{[...data.ecom.map(x=>[x,'ecom'] as const),...data.ecomAmendments.map(x=>[x,'ecomAmendments'] as const)].map(([r,name])=><div key={r.id} className="grid grid-cols-2 md:grid-cols-6 gap-2 p-3 bg-slate-950 rounded-xl border border-slate-800">{field('ECO GSTIN',r.etin,v=>update({...data,[name]:(data[name] as Gstr1EcomRow[]).map(x=>x.id===r.id?{...x,etin:v}:x)}))}{field('Type',r.typ,v=>update({...data,[name]:(data[name] as Gstr1EcomRow[]).map(x=>x.id===r.id?{...x,typ:v as any}:x)}))}{field('POS',r.pos,v=>update({...data,[name]:(data[name] as Gstr1EcomRow[]).map(x=>x.id===r.id?{...x,pos:v}:x)}))}{field('Taxable',r.txval,v=>update({...data,[name]:(data[name] as Gstr1EcomRow[]).map(x=>x.id===r.id?{...x,txval:num(v)}:x)}),'number')}{field('Rate',r.rt,v=>update({...data,[name]:(data[name] as Gstr1EcomRow[]).map(x=>x.id===r.id?{...x,rt:num(v)}:x)}),'number')}{field('IGST',r.iamt,v=>update({...data,[name]:(data[name] as Gstr1EcomRow[]).map(x=>x.id===r.id?{...x,iamt:num(v)}:x)}),'number')}<button onClick={()=>remove(name,r.id)} className="text-rose-400"><Trash2 className="w-3.5 h-3.5"/></button></div>)}</div>}

    <div className="border-t border-slate-800 pt-4 flex flex-col lg:flex-row gap-3 lg:items-center lg:justify-between"><div className="text-xs text-slate-400"><FileText className="w-4 h-4 inline mr-1 text-emerald-400"/>Sections entered: <strong className="text-white">{Object.values(data).reduce((a,v)=>a+v.length,0)}</strong>. Data is stored per GSTIN and return period.</div><details className="max-w-full"><summary className="cursor-pointer text-xs text-blue-400">Preview Full JSON</summary><pre className="mt-2 max-h-72 overflow-auto bg-slate-950 p-3 rounded-lg text-[10px] text-emerald-300">{JSON.stringify(fullJson,null,2)}</pre></details></div>
  </div>;
};
